---
title: "quarto"
author: "Amandine & Joaquim"
format: html
editor: visual
---

## Configuration

[Link github repository](https://github.com/JoaquimBamba/project)

```{r echo=FALSE,message=False, warning=FALSE}

library(here)
library(ggplot2)
library(tidyr)
library(dplyr)

here::i_am("project.Rproj")
```

## Data importation
```{r}
co2 <- vroom::vroom(here("data/CO2.csv"), show_col_types = FALSE)
energy_consumption <- vroom::vroom(here("data/Energy_consumption.csv"),show_col_types = FALSE)
gdp_growth <- vroom::vroom(here("data/GDP_growth.csv"), delim=",",show_col_types = FALSE)
gdp <- vroom::vroom(here("data/GDP.csv"),delim=",",show_col_types = FALSE)
gdp_by_sector <- vroom::vroom(here("data/GDP_composition_by_sector_of_origin.csv"),show_col_types = FALSE)
gross_capital <- vroom::vroom(here("data/Gross_capital_formation.csv"),delim=",",show_col_types = FALSE)
population_growth <- vroom::vroom(here("data/POP_growth.csv"),delim=",",show_col_types = FALSE)
urban_population <- vroom::vroom(here("data/Urban_population.csv"),delim=",",show_col_types = FALSE)
alternative_energy_consumption <- vroom::vroom(here("data/Alternative_nuclear_energy_consumption.csv"),delim=",",show_col_types = FALSE)
fossil_energy_consumption <- vroom::vroom(here("data/Fossil_fuel_energy_consumption.csv"),delim=",",show_col_types = FALSE)
```

